site_name: distsfactory
site_description: Construct probability distributions from partial specifications
repo_url: https://github.com/yoninazarathy/distsfactory-python

theme:
  name: material
  palette:
    scheme: default

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
