"""Cross-package numerical tests against the Julia reference oracle.

The oracle (``tests/data/cross_oracle.json``) is generated by running

    julia --project=. scripts/build_cross_oracle.jl

inside the sibling DistributionsFactories.jl repo (see
https://github.com/Distribution-Matching/DistributionsFactories.jl). That
script writes oracle files into both this package and the sibling R package
in a single invocation. For each (canonical_name, kwargs) pair in the oracle,
this test runs ``make_dist`` in Python and verifies the resulting moments
(and continuous-distribution quantiles) match the Julia reference within a
generous tolerance.

If the oracle file is missing the test suite skips — the oracle is checked in,
but anyone editing it should regenerate after a change.
"""

import json
import math
import pathlib

import pytest
from distsfactory import make_dist, dist_exists


ORACLE = pathlib.Path(__file__).parent / "data" / "cross_oracle.json"


def _load_oracle():
    if not ORACLE.exists():
        pytest.skip(
            f"Oracle missing: {ORACLE}. "
            "Regenerate by running scripts/build_cross_oracle.jl."
        )
    data = json.loads(ORACLE.read_text())
    # Backward compat: older oracles were a flat list of constructor cases.
    if isinstance(data, list):
        return {"constructors": data, "feasibility": []}
    return data


def _coerce_kwargs(kw):
    """Convert JSON-encoded kwargs back to Python types.

    The Julia oracle emits ``quantiles`` as a list of two-element lists; we
    coerce those back to a list of tuples so they match the Python API
    signature exactly.
    """
    out = {}
    for k, v in kw.items():
        if k == "quantiles":
            out[k] = [tuple(pair) for pair in v]
        else:
            out[k] = v
    return out


def _parse_value(x):
    if isinstance(x, str):
        if x == "inf":
            return math.inf
        if x == "-inf":
            return -math.inf
        if x == "nan":
            return math.nan
    return float(x)


def _make_id(case):
    kw_str = ",".join(f"{k}={v}" for k, v in case["kwargs"].items())
    return f"{case['py_name']}({kw_str})"


ORACLE_DATA = _load_oracle()
CASES = ORACLE_DATA["constructors"]
FEAS_CASES = ORACLE_DATA["feasibility"]


def _parse_support(s):
    if s is None:
        return None
    lo, hi = _parse_value(s[0]), _parse_value(s[1])
    return (lo, hi)


def _feas_id(case):
    kw_str = ",".join(f"{k}={v}" for k, v in case["kwargs"].items())
    sup = f",support={case['support']}" if case["support"] is not None else ""
    return f"{case['py_name']}({kw_str}{sup})->{case['expected']}"


@pytest.mark.parametrize("case", CASES, ids=_make_id)
def test_cross_julia(case):
    name = case["py_name"]
    kwargs = _coerce_kwargs(case["kwargs"])
    expected = case["expected"]
    is_discrete = expected["discrete"]

    d = make_dist(name, **kwargs)

    # Mean / var: both packages should agree to ~1e-6 relative for closed-form
    # families. Numerical families (Weibull, Frechet, FoldedNormal, mode-based,
    # 2-quantile Beta) may have slightly larger differences from independent
    # root-finder paths; we use rel_tol=1e-5 across the board.
    expected_mean = _parse_value(expected["mean"])
    expected_var = _parse_value(expected["var"])

    if math.isfinite(expected_mean):
        assert math.isclose(d.mean(), expected_mean, rel_tol=1e-5, abs_tol=1e-9), \
            f"{name} {kwargs}: mean Python={d.mean()} vs Julia={expected_mean}"
    if math.isfinite(expected_var):
        assert math.isclose(d.var(), expected_var, rel_tol=1e-5, abs_tol=1e-9), \
            f"{name} {kwargs}: var Python={d.var()} vs Julia={expected_var}"

    # Quantile check (continuous only): discrete distributions disagree on
    # ties between scipy and Distributions.jl conventions; that is not a bug
    # so we skip.
    if not is_discrete and "ppf" in expected:
        for p_str, q_jl in expected["ppf"].items():
            p = float(p_str)
            q_jl = _parse_value(q_jl)
            if not math.isfinite(q_jl):
                continue
            q_py = float(d.ppf(p))
            assert math.isclose(q_py, q_jl, rel_tol=1e-5, abs_tol=1e-7), \
                f"{name} {kwargs}: ppf({p}) Python={q_py} vs Julia={q_jl}"


@pytest.mark.parametrize("case", FEAS_CASES, ids=_feas_id)
def test_cross_julia_feasibility(case):
    """Verify dist_exists() returns the same bool as the Julia reference."""
    name = case["py_name"]
    kwargs = _coerce_kwargs(case["kwargs"])
    expected = case["expected"]
    support = _parse_support(case["support"])

    if support is None:
        actual = dist_exists(name, **kwargs)
    else:
        actual = dist_exists(name, support=support, **kwargs)

    assert actual is expected, \
        f"{name} {kwargs} support={support}: Python={actual} vs Julia={expected}"
